function [ll] = GMM_loglikelihood(X, theta)
% Calculate the log likelihood of X, given a mixture model.
% 
% The model assumes each column of x is independently generated by a
% mixture model with parameters theta.
%
% Arguments
%  X - A DxM matrix, whose every column corresponds to a patch in D
%      dimensions (typically D=64).
%  theta - A struct with fields:
%          means - A KxD matrix where K is the number of components in
%                  mixture and D is the dimension of the data.
%          covs - A DxDxK array whose every page is a covariance matrix of
%                 the corresponding component.
%          mix - A Kx1 vector with mixing proportions.
%
K = size(theta.mix,1);
M = size(X, 2);

means = theta.means;
covs = theta.covs;
mix = theta.mix;

logDensXgivenH = zeros(M,K);
for k = 1:K
    logDensXgivenH(:,k) = log_mvnpdf(X', means(k,:), covs(:,:,k));   
end

logmatProbH = repmat(log(mix), 1, M)';

logProbX = logsum(logDensXgivenH + logmatProbH, 2);

ll = sum(logProbX);


