function [xhat] = ICA_denoise(y, ica, noise)
% Denoises every column in y, assuming an ICA model and white noise.
% 
% The model assumes that y = x + noise where x is generated by a ICA
% 0-mean mixture model.
%
% Arguments
%  y - A DxM matrix, whose every column corresponds to a patch in D
%      dimensions (typically D=64).
%  ica - A struct with fields:
%           P - mixing matrix of sources (P: D ind. sources -> D signals)
%           vars - a DxK matrix whose (d,k) element correponsds to the
%                  variance of the k'th component in dimension d.
%           mix - a DxK matrix whose (d,k) element correponsds to the
%                 mixing weight of the k'th component in dimension d.
%  noise - the std of the noise in y.
%

% initialize variables
[D, K] = size(ica.vars);
M = size(y, 2);
P = ica.P;
t = P' * y;
shat = zeros(D, M);

% denoise each component separately
gmm.means = zeros(K, 1);
for i = 1:D
	gmm.mix = ica.mix(i,:)';
	icaVarsI = ica.vars(i,:);
	gmm.covs = reshape(icaVarsI, [1 1 K]);
	shat(i,:) = GMM_denoise(t(i,:), gmm, noise);
end

% transform shat to xhat
xhat = P * shat;
