function [ll] = ICA_loglikelihood(X, model)
% Calculate the log likelihood of X, given an ICA model.
% 
% The model assumes each column of x is independently generated by a
% mixture model with parameters theta.
%
% Arguments
%  X - A DxM matrix, whose every column corresponds to a patch in D
%      dimensions (typically D=64).
%  model - A struct with fields:
%           P - mixing matrix of sources (P: D ind. sources -> D signals)
%           vars - a DxK matrix whose (d,k) element correponsds to the
%                  variance of the k'th component in dimension d.
%           mix - a DxK matrix whose (d,k) element correponsds to the
%                 mixing weight of the k'th component in dimension d.
%

% initialize variables
S = model.P' * X;
D = size(X, 1);
ll = 0;
K = size(model.vars, 2);

% sum the loglikelihoods of S's components
theta.means = zeros(K, 1);
for i = 1:D
	theta.covs = reshape(model.vars(i,:), [1 1 K]);
	theta.mix = model.mix(i,:)';
	ll = ll + GMM_loglikelihood(S(i,:), theta);
end
